version: "3.7"

volumes:
  trust-volume:
  grid-certs:

services:
  trust:
    image: alpine
    command: /bin/sh -c "
        wget \"http://repository.egi.eu/sw/production/cas/1/current/tgz/\" &&
        mkdir tgz && for tgz in $$(cat index.html | awk -F'\"' '{print $$2}' | grep tar.gz);
        do wget http://repository.egi.eu/sw/production/cas/1/current/tgz/$$tgz -O tgz/$$tgz;
        done && for tgz in $$(ls tgz/); do tar xzf tgz/$$tgz --strip-components=1 -C certificates/;
        done && for f in $$(find certificates/ -type f -name \"*.pem\");
        do cat $$f >> /certs/ca-certificates.crt; done &&
        wget \"https://crt.sh/?d=2475254782\" -O /certs/geant-ov-rsa-ca.crt &&
        wget \"http://131.154.97.87:8080/certs/chain1.pem\" -O /certs/chain1.crt &&
        cat /certs/geant-ov-rsa-ca.crt >> /certs/ca-certificates.crt &&
        cat /certs/chain1.crt >> /certs/ca-certificates.crt &&
        nc -l -p 8085
      "
    volumes:
      - trust-volume:/certs
      - grid-certs:/certificates

  client:
    image: ffornari/gfal2-oidc:${IMAGE_TAG}
    container_name: client
    command: /bin/sh -c "
        /scripts/wait-for-it.sh -t 0 trust:8085 &&
        eval $(oidc-agent-service use) &&
        oidc-gen --scope-all --confirm-default --iss=https://$IAM_HOST/ docker &&
        export BEARER_TOKEN=$(oidc-token docker) &&
        gfal-ls -lH https://$WEBDAV_HOST/$STORAGE_AREA &&
        gfal-copy /etc/services https://$WEBDAV_HOST/$STORAGE_AREA/testfile &&
        gfal-ls -lH https://$WEBDAV_HOST/$STORAGE_AREA &&
        gfal-rm https://$WEBDAV_HOST/$STORAGE_AREA/testfile &&
        gfal-ls -lH https://$WEBDAV_HOST/$STORAGE_AREA &&
        tail -f /dev/null
      "
    extra_hosts:
      - "${IAM_HOST}:${IAM_IP}"
    links:
      - "trust:trust"
    environment:
      IAM_HOST: ${IAM_HOST}
      WEBDAV_HOST: ${WEBDAV_HOST}
      STORAGE_AREA: ${STORAGE_AREA}
      OIDC_ENCRYPTION_PW: ${OIDC_ENCRYPTION_PW}

    volumes:
      - trust-volume:/etc/ssl/certs
      - grid-certs:/etc/grid-security/certificates
      - ./scripts/wait-for-it.sh:/scripts/wait-for-it.sh

    depends_on:
      - trust
